### ISSUE TITLE
Impossible to build on Android

### ISSUE THREAD

**Issue by AdrienV** [devin-la/ionic-video-chat-v2-issues#108]
Hello,

For me, impossible to build on android. 
Everything good on iOs, server config seems to be okay, but I get this error for Android : 

> [23:00:51]  lint finished in 19.21 s 
> ANDROID_HOME=/Users/adrienv/Library/Android/sdk
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
> > Task :wrapper
> 
> BUILD SUCCESSFUL in 9s
> 1 actionable task: 1 executed
> Subproject Path: CordovaLib
> null
> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
> 
> 	at build_achw65lazzqxqumdojn4911io.run(/Users/adrienv/NoiCloud/videoChat/ionic-video-chat-v2-3.0.1/platforms/android/build.gradle:142)
> 
> org.xwalk:xwalk_core_library:23+
> 
> Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html
> 
> * Try:
> Run with --stacktrace
>  option to get the stack trace. Run with --info or 
> --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 8s
> (node:36433) UnhandledPromiseRejectionWarning: Error: /Users/adrienv/NoiCloud/videoChat/ionic-video-chat-v2-3.0.1/platforms/android/gradlew: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'android'.
> > All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 8s
>     at ChildProcess.whenDone (/Users/adrienv/NoiCloud/videoChat/ionic-video-chat-v2-3.0.1/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
>     at ChildProcess.emit (events.js:180:13)
>     at maybeClose (internal/child_process.js:936:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> (node:36433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:36433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any idea ?

// I tried to add platform with android@7.0.0 and with android@6.4.0, this is the error for android@6.4.0

Thanks.

**Comment by whatnowangga** [comment]
this is something error in xwalk. you must change something in android studio project
