### ISSUE TITLE
Local testing issues

### ISSUE THREAD

**Issue by pareklinon** [devin-la/ionic-video-chat-v2-issues#97]
After ionic serve run I get the info the app I can tap the contact icon and the chat icon but the divs are empty. What am I doing wrong?
Also when I build it with xcode I get a lot of swift errors (xCode 9.1) I managed to successfully build it but when it loads on an iphone I get the same results (empty pages with a view of chat and contact buttons.

`Starting app-scripts server: --address 0.0.0.0 --port 8100 --livereload-port 35729 --dev-logger-port 53703 
--nobrowser - Ctrl+C to cancel
[10:10:04]  watch started ... 
[10:10:04]  build dev started ... 
[10:10:04]  clean started ... 
[10:10:04]  clean finished in 4 ms 
[10:10:04]  copy started ... 
[10:10:04]  deeplinks started ... 
[10:10:04]  deeplinks finished in 131 ms 
[10:10:04]  transpile started ... 
[10:10:07]  transpile finished in 3.24 s 
[10:10:07]  preprocess started ... 
[10:10:07]  preprocess finished in 1 ms 
[10:10:07]  webpack started ... 
[10:10:07]  copy finished in 3.54 s 
[10:10:16]  webpack finished in 8.82 s 
[10:10:16]  sass started ... 
[10:10:17]  sass finished in 1.10 s 
[10:10:17]  postprocess started ... 
[10:10:17]  postprocess finished in 7 ms 
[10:10:17]  lint started ... 
[10:10:17]  build dev finished in 13.40 s 
[10:10:17]  watch ready in 13.47 s 
[10:10:17]  dev server running: http://localhost:8100/ 

[OK] Development server running!
     Local: http://localhost:8100
     External: http://192.168.70.50:8100
     DevApp: ionic-video-chat-3@8100 on obss-mbp

[10:10:20]  tslint: src/services/video.ts, line: 51 
            'getDevices' is declared but never used. 

      L50:  };
      L51:  var getDevices = () => {
      L52:  	navigator.mediaDevices.enumerateDevices().then(data => {

[10:10:20]  tslint: src/services/video.ts, line: 5 
            All imports are unused. 

       L4:  import { Platform } from 'ionic-angular';
       L5:  import { Events } from 'ionic-angular';

[10:10:20]  tslint: src/services/chat.ts, line: 15 
            Property 'zone' is declared but never used. 

      L14:  // manages chats
      L15:  constructor(private zone:NgZone, private ref: ApplicationRef, private socket: SocketService, private events:
      L16:  	let evts = events;

[10:10:20]  tslint: src/services/chat.ts, line: 185 
            'self' is declared but never used. 

     L184:  get(chatId) {
     L185:  	let self = this;
     L186:  	return new Promise((resolve, reject) => {

[10:10:20]  tslint: src/services/login.ts, line: 160 
            'cleanA' is declared but never used. 

     L160:  var cleanA = self.events.subscribe('user.login', data => {
     L161:  	//cleanA(); cleanB();

[10:10:20]  tslint: src/services/login.ts, line: 164 
            'cleanB' is declared but never used. 

     L163:  });
     L164:  var cleanB = self.events.subscribe('auth', () => {
     L165:  	//cleanA(); cleanB();

[10:10:20]  tslint: src/services/login.ts, line: 3 
            'ViewChild' is declared but never used. 

       L3:  import { Injectable, ViewChild } from '@angular/core';
       L4:  import { Events, Nav, NavController, AlertController, App, Platform } from 'ionic-angular';

[10:10:20]  tslint: src/services/login.ts, line: 4 
            'Nav' is declared but never used. 

       L3:  import { Injectable, ViewChild } from '@angular/core';
       L4:  import { Events, Nav, NavController, AlertController, App, Platform } from 'ionic-angular';
       L5:  import { AudioService, SocketService, ContactService } from './';

[10:10:20]  tslint: src/services/attachment.ts, line: 11 
            Property 'events' is declared but never used. 

      L10:  export class AttachmentService {
      L11:  ctor(public platform: Platform, private socket: SocketService, private http: Http, private events: Events) {

[10:10:20]  tslint: src/services/attachment.ts, line: 5 
            All imports are unused. 

       L4:  import { Platform, Events } from 'ionic-angular';
       L5:  import { Config } from '../app/config';
       L6:  import { SocketService } from '../services';

[10:10:20]  tslint: src/services/attachment.ts, line: 7 
            'Response' is declared but never used. 

       L6:  import { SocketService } from '../services';
       L7:  import { Http, Response, Headers, RequestOptions } from '@angular/http';

[10:10:20]  tslint: src/services/attachment.ts, line: 7 
            'Headers' is declared but never used. 

       L6:  import { SocketService } from '../services';
       L7:  import { Http, Response, Headers, RequestOptions } from '@angular/http';

[10:10:20]  tslint: src/services/attachment.ts, line: 7 
            'RequestOptions' is declared but never used. 

       L6:  import { SocketService } from '../services';
       L7:  import { Http, Response, Headers, RequestOptions } from '@angular/http';

[10:10:20]  tslint: src/components/call-modal/call-modal.ts, line: 3 
            'Input' is declared but never used. 

       L3:  import { Component, Input } from '@angular/core';
       L4:  import { ModalController, NavParams, Events, ViewController} from 'ionic-angular';

[10:10:20]  tslint: src/components/call-modal/call-modal.ts, line: 4 
            'ModalController' is declared but never used. 

       L3:  import { Component, Input } from '@angular/core';
       L4:  import { ModalController, NavParams, Events, ViewController} from 'ionic-angular';
       L5:  import { CallService } from '../../services/call';

[10:10:20]  tslint: src/components/contact-add-modal/contact-add-modal.ts, line: 15 
            Property 'contactService' is declared but never used. 

      L15:  vate viewCtrl: ViewController, private modalCtrl: ModalController, private contactService: ContactService) {
      L16:  		this.contacts = contactService.contacts;

[10:10:20]  tslint: src/components/call-modal/call-modal-trigger.ts, line: 4 
            'ViewController' is declared but never used. 

       L3:  import { Injectable } from '@angular/core';
       L4:  import { ModalController, Events, ViewController} from 'ionic-angular';
       L5:  import { CallModal } from '../../components';

[10:10:20]  tslint: src/components/keyboard-attach/keyboard-attach.ts, line: 4 
            All imports are unused. 

       L3:  import { Keyboard } from '@ionic-native/keyboard';
       L4:  import { Subscription } from 'rxjs/rx';

[10:10:20]  tslint: src/pages/chats/chats.ts, line: 12 
            Property 'zone' is declared but never used. 

      L11:  export class ChatsPage {
      L12:  	constructor(private zone: NgZone, private events:Events, public chatService: ChatService, private navCtrl: 
      L13:  		// contacts / chats list state

[10:10:20]  tslint: src/pages/chats/chats.ts, line: 12 
            Property 'events' is declared but never used. 

      L11:  export class ChatsPage {
      L12:  	constructor(private zone: NgZone, private events:Events, public chatService: ChatService, private navCtrl: 
      L13:  		// contacts / chats list state

[10:10:20]  tslint: src/pages/chats/chats.ts, line: 12 
            Property 'loginService' is declared but never used. 

      L11:  export class ChatsPage {
      L12:  ents, public chatService: ChatService, private navCtrl: NavController, private loginService: LoginService) {
      L13:  		// contacts / chats list state

[10:10:20]  tslint: src/pages/chats/chats.ts, line: 4 
            All imports are unused. 

       L3:  import { ChatPage, AccountPage, ContactsPage } from '../';
       L4:  import { ContactModal } from '../../components';
       L5:  import { LoginService, ChatService } from '../../services';

[10:10:20]  tslint: src/pages/login/login.ts, line: 8 
            'window' is declared but never used. 

       L8:  declare var window:any;

[10:10:20]  tslint: src/pages/chat/chat.ts, line: 15 
            'document' is declared but never used. 

      L15:  declare var document: any;
      L16:  declare var $: any;

[10:10:20]  tslint: src/pages/chat/chat.ts, line: 43 
            Property 'sanitizer' is declared but never used. 

      L43:  	constructor(private sanitizer: DomSanitizer, private attachment: AttachmentService, public contactService: 
      L44:  		console.debug('Viewing chat: ', params.get('chatId'));

[10:10:20]  tslint: src/pages/chat/chat.ts, line: 10 
            All imports are unused. 

      L10:  import { Observable } from 'rxjs/Observable';

[10:10:20]  tslint: src/pages/contacts/contacts.ts, line: 15 
            Property 'loginService' is declared but never used. 

      L15:  l: ModalController, private navCtrl: NavController, private loginService: LoginService, public contactServic
      L16:  		// contacts / chats list state

[10:10:20]  tslint: src/app/app.component.ts, line: 1 
            'ViewChild' is declared but never used. 

       L1:  import { Component, ViewChild } from '@angular/core';
       L2:  import { Platform, NavController, Nav , ViewController, Events } from 'ionic-angular';

[10:10:20]  tslint: src/app/app.component.ts, line: 2 
            'NavController' is declared but never used. 

       L1:  import { Component, ViewChild } from '@angular/core';
       L2:  import { Platform, NavController, Nav , ViewController, Events } from 'ionic-angular';

[10:10:20]  tslint: src/app/app.component.ts, line: 2 
            'Nav' is declared but never used. 

       L1:  import { Component, ViewChild } from '@angular/core';
       L2:  import { Platform, NavController, Nav , ViewController, Events } from 'ionic-angular';

[10:10:20]  tslint: src/app/app.component.ts, line: 2 
            'ViewController' is declared but never used. 

       L1:  import { Component, ViewChild } from '@angular/core';
       L2:  import { Platform, NavController, Nav , ViewController, Events } from 'ionic-angular';

[10:10:20]  lint finished in 2.54 s 

`

When I tap the settings button on the app I get the following error message (in Chrome)

Error
Close
Runtime Error
Cannot read property 'name' of null
Stack
TypeError: Cannot read property 'name' of null
    at Object.eval [as updateRenderer] (ng:///AppModule/AccountPage.ngfactory.js:69:31)
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:8100/build/vendor.js:13489:21)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12633:14)
    at callViewAction (http://localhost:8100/build/vendor.js:12996:21)
    at execComponentViewsAction (http://localhost:8100/build/vendor.js:12928:13)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12634:5)
    at callViewAction (http://localhost:8100/build/vendor.js:12996:21)
    at execEmbeddedViewsAction (http://localhost:8100/build/vendor.js:12954:17)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12629:5)
    at callViewAction (http://localhost:8100/build/vendor.js:12996:21)
Ionic Framework: 3.8.0
Ionic App Scripts: 3.0.1
Angular Core: 4.4.4
Angular Compiler CLI: 4.4.4
Node: 6.11.1
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

![2017-12-06 10 19 35](https://user-images.githubusercontent.com/25724979/33651569-0682b85e-da6f-11e7-8003-eb6a9a499f80.png)

**Comment by spacedevin** [comment]
looks like the ionic part is working all fine. you just need to connect it to your server.
see https://github.com/devin-la/ionic-video-chat-support/wiki/Config and https://github.com/devin-la/ionic-video-chat-support/wiki/Server#local-setup

**Comment by pareklinon** [comment]
I followed all your well-described steps but no luck getting it work. Waiting for your reply. 
Thank you!

**Comment by spacedevin** [comment]
what is your error? according to the above logs there is nothing wrong with the frontend. it is not connecting to the server. can you please paste your server logs?

**Comment by bigroski** [comment]
Hi i am having the same problem. How can i check for errors and server log?
