### ISSUE TITLE
Issues in initiating chat

### ISSUE THREAD

**Issue by rkalra7** [devin-la/ionic-video-chat-v2-issues#98]
I am using the latest build.
Problem is that post registration of users, if I try to initiate a chat session, the html spurts error saying that "cannot read property name of 'null'".
This is because getChatById method called in chatService inside constructor for ChatPage returns null.

Just in case you need this:
TypeError: Cannot read property 'name' of null
    at Object.eval [as updateRenderer] (ng:///AppModule/ChatPage.ngfactory.js:359:30)
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:8100/build/vendor.js:13489:21)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12633:14)
    at callViewAction (http://localhost:8100/build/vendor.js:12996:21)
    at execComponentViewsAction (http://localhost:8100/build/vendor.js:12928:13)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12634:5)
    at callViewAction (http://localhost:8100/build/vendor.js:12996:21)
    at execEmbeddedViewsAction (http://localhost:8100/build/vendor.js:12954:17)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:12629:5)
    at callViewAction (http://localhost:8100/build/vendor.js:12996:21)

**Comment by spacedevin** [comment]
take a look at https://github.com/devin-la/ionic-video-chat-support/issues/61 and let me know if that fixes it for you

**Comment by rkalra7** [comment]
Great. That fixed it. Cheers!
